### ISSUE TITLE
Submit as a patch to https://phabricator.kde.org/

### ISSUE THREAD

**Issue by Pointedstick** [FadySGhatas/kde-dolphin-single-instance#1]
Can you please submit this as a patch to https://phabricator.kde.org/?

**Comment by FadySGhatas** [comment]
I submitted that before for review and some modifications were required, kept trying to free some time to look into that but unfortunately haven't had any time to work on it.

Anyways, @intika took over and his repo is now ready to shipped:
https://github.com/intika/kde-dolphin-single-instance

I think it complies with all required modifications.

**Comment by Pointedstick** [comment]
@intika, would you please submit it as a patch? No KDE developer is going to come over to your repo. You can see our documentation for the process here: https://community.kde.org/Infrastructure/Phabricator

**Comment by intika** [comment]
@Pointedstick i did not do it because the implementation was in alpha because it had a serious issue where when you open a folder from different context like command line etc. it opened a new instance of dolphin... so i waited to solve this before submitting anything... i did solve it last week locally... and it seem to work... i will submit a patch soon ;)

**Comment by Pointedstick** [comment]
Awesome, thanks!
